[functions]
directory = "functions"
[functions."generate"]
schedule = "5 17 * * *"
[context.data]
publish = "dist"
command = ""
functions = ""
[[headers]]
  for = "/data/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
