[context.data]
publish = "dist"
command = "node --version"
functions = ""
[[headers]]
  for = "/*.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/today.json"
    [headers.values]
    Cache-Control = "public"
