[functions]
directory = "functions"
[functions."generate"]
schedule = "0 4 * * *"
[context.data]
publish = "dist"
command = ""
functions = ""
[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = '''
  public,
  max-age=31536000,
  immutable'''
[[headers]]
  for = "/*.png"
    [headers.values]
    Cache-Control = '''
  public,
  max-age=604800'''
